# Generated by Django 5.1.5 on 2025-06-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='youtubevideo',
            name='file_path',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='audio_file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='audio_file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
