# Generated by Django 5.1.4 on 2025-06-22 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0002_remove_youtubevideo_file_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("artists", models.JSONField(default=list)),
                ("album", models.CharField(blank=True, max_length=500)),
                ("duration_ms", models.IntegerField(null=True)),
                (
                    "spotify_id",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("isrc", models.CharField(blank=True, db_index=True, max_length=20)),
                ("external_ids", models.JSONField(default=dict)),
                ("genres", models.JSONField(default=list)),
                ("release_date", models.CharField(blank=True, max_length=20)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title", "artists"],
                "indexes": [
                    models.Index(
                        fields=["title", "artists"], name="recognition_title_32cca2_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("spotify_id", "")),
                        fields=("title", "artists"),
                        name="unique_song_without_spotify_id",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="recognitionresult",
            name="song",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recognition_results",
                to="recognition.song",
            ),
        ),
        migrations.AddIndex(
            model_name="recognitionresult",
            index=models.Index(fields=["song"], name="recognition_song_id_83cd73_idx"),
        ),
    ]
