# Generated by Django 5.1.4 on 2025-06-22 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0004_migrate_songs_data"),
    ]

    operations = [
        # First, alter the song field to be non-nullable
        migrations.AlterField(
            model_name='recognitionresult',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_results', to='recognition.song'),
        ),
        # Remove old indexes
        migrations.RemoveIndex(
            model_name='recognitionresult',
            name='recognition_spotify_e97d2c_idx',
        ),
        migrations.RemoveIndex(
            model_name='recognitionresult',
            name='recognition_title_f216ad_idx',
        ),
        # Update unique_together
        migrations.AlterUniqueTogether(
            name='recognitionresult',
            unique_together={('video', 'timestamp_start', 'song')},
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name='recognitionresult',
            name='album',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='duration_ms',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='external_ids',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='isrc',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='label',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='spotify_id',
        ),
        migrations.RemoveField(
            model_name='recognitionresult',
            name='title',
        ),
    ]