# Generated by Django 5.1.4 on 2025-06-22 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0005_remove_old_song_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                (
                    "spotify_id",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("genres", models.JSONField(default=list)),
                ("popularity", models.IntegerField(blank=True, null=True)),
                ("external_urls", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="song",
            name="artist_set",
            field=models.ManyToManyField(
                blank=True, related_name="songs", to="recognition.artist"
            ),
        ),
    ]
