# Generated by Django 5.1.4 on 2025-06-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0006_artist_song_artist_set"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="artist_set",
        ),
    ]
