# Generated by Django 5.1.4 on 2025-06-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0007_remove_song_artist_set"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recognitionresult",
            options={},
        ),
        migrations.AlterModelOptions(
            name="song",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="song",
            name="unique_song_without_spotify_id",
        ),
        migrations.RemoveIndex(
            model_name="recognitionresult",
            name="recognition_song_id_83cd73_idx",
        ),
        migrations.RemoveIndex(
            model_name="song",
            name="recognition_title_32cca2_idx",
        ),
        migrations.AlterUniqueTogether(
            name="recognitionresult",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="song",
            name="artists",
        ),
        migrations.AddField(
            model_name="song",
            name="artist_set",
            field=models.ManyToManyField(
                blank=True, related_name="songs", to="recognition.artist"
            ),
        ),
    ]
