# Generated by Django 5.1.5 on 2025-07-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0008_alter_recognitionresult_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='dancers',
            field=models.ManyToManyField(blank=True, related_name='videos', to='recognition.dancer'),
        ),
    ]
