# Generated by Django 5.1.4 on 2025-08-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recognition", "0010_edition_event_song_edition_edition_event_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="edition",
        ),
        migrations.AddField(
            model_name="recognitionresult",
            name="edition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recognition_results",
                to="recognition.edition",
            ),
        ),
    ]
